# Generated by Django 4.2.11 on 2026-02-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_mensajecontacto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajecontacto',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
