# Generated by Django 6.0.2 on 2026-02-07 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la práctica')),
                ('horas', models.DecimalField(decimal_places=2, help_text='Ejemplo: 6.5', max_digits=4)),
                ('tareas', models.TextField(verbose_name='Tareas realizadas')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones / Aprendizaje')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicas.alumno')),
            ],
            options={
                'verbose_name': 'Entrada del Diario',
                'verbose_name_plural': 'Entradas del Diario',
                'ordering': ['-fecha'],
            },
        ),
    ]
