# Generated by Django 6.0 on 2026-02-11 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicas', '0002_entradadiario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='tutor_asignado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumnos_a_cargo', to='practicas.profesor', verbose_name='Tutor Laboral'),
        ),
    ]
