# Generated by Django 4.2.11 on 2026-02-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicas', '0004_alter_alumno_id_alter_empresa_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entradadiario',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
